jobs:
  test:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: run tests
orbs:
  node: 'circleci/node:x.y'
version: 2.1
workflows:
  fictional-train:
    jobs:
      - test
