jobs:
  checkout:
    working_directory: ~/repo
    executor:
      name: node/default
      tag: '14.10'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - persist_to_workspace:
          root: ~/repo

  lint:
    working_directory: ~/repo
    executor:
      name: node/default
      tag: '14.10'
    steps:
      - run:
          command: yarn tslint
          name: run tslint

  test:
    working_directory: ~/repo
    executor:
      name: node/default
      tag: '14.10'
    steps:
      - run:
          command: yarn test
          name: run tests

orbs:
  node: circleci/node@4.0.0
version: 2.1
workflows:
  fictional-train:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - test:
          requires:
            - lint
